apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: expense
spec:
  storageClassName: "expense-ebs" 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      component: mysql
      project: expense
      tier: db
  serviceName: "nginx"
  replicas: 3 # by default is 1
   template:
     metadata:
       labels:
         component: mysql
         project: expense
         tier: db
      spec:
        containers:
        - name: mysql
          image: joindevops/mysql:v1.0
          ports:
          - containerPort: 80
            name: web
          volumeMounts:
          - name: mysql
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql
          persistentVolumeClaim:
            claimName: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec: 
  clusterIP: None # which is headless
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
